### ISSUE TITLE
Ndarray/Ndarray-rand versions mismatch

### ISSUE THREAD

**Issue by relf** [argmin-rs/argmin#108]
As I try to upgrade `linfa` to `ndarray 0.14` (cf. https://github.com/rust-ml/linfa/pull/110), I noticed that `argmin 0.4.2` has `ndarray 0.14` and `ndarray-rand 0.14` dependencies. 

Unfortunately `ndarray-rand 0.14` depends on `ndarray 0.15`, it should be `ndarray-rand 0.13` to depend on`ndarray 0.14`.

It could explain the compilation problems I get (?) Strangely even if I specify `argmin 0.4.1` it pulls `argmin 0.4.2` (not sure what is going on here!).

I would suggest to release `argmin 0.4.3` reverting `ndarray-rand` to `0.13`.

**Comment by stefan-k** [comment]
Thanks! I just released 0.4.3.
