### ISSUE TITLE
Performance Enhancements

### ISSUE THREAD

**Issue by sdd** [argmin-rs/argmin#111]
First of all, I'd like to thank everyone involved in making this crate. I've been using it in multiple places in a project of mine for the past few months, and I love the ergonomics and find the crate a joy to use - Kudos!

Anyway, I was doing some performance tuning on my code recently and discovered that in my calls to `Executor::run`, only about 44% of processor time was spent inside my `ArgminOp::apply`. When looking at where the rest of the time was being spent, I noticed three main areas:

1. `alloc::fmt::format`, `ArgminKV::merge`, and `drop ArgminKV`. This would be expected if I was using an observer, but this overhead happens even with no registered observers.
2. `Instant::elapsed` and `Instant::now`. These are called even if I don't care about the elapsed time (as is often the case once I've finished tuning the optimisation params)`.
3. `ArgminCheckpoint::store_cond`. This allocates a string, concats it with another string, and deallocs the result on exit - every single time through the `Executor::run` loop, even if Checkpoints are off, or this loop is not a checkpointed loop.

Here's a section of my flamechart from cargo-flamechart to illustrate this.
Green boxes highlight my code inside the apply function, magenta is for point (1) above, red for point (2), and blue for point (3)

![image](https://user-images.githubusercontent.com/323439/116487949-1cacba80-a889-11eb-9c70-da286b835746.png)

I've got a branch in my fork where I've addressed points (1) and (3) by some refactoring, which I don't think will cause any issues (but you all know better than me, I may be wrong!). I've also addressed (2) by introducing a config flag to make the timer optional, similarly to how enabling/disabling Ctrl-C works. You can see my changes here: https://github.com/sdd/argmin/commit/a67f56a1313aea7dfbd7f14459942bbd7ae2182b

With the modifications above in place, I get a 44% speedup, and I can see that the executor now spends 93% of its time running my `ArgminOp::apply`, rather than 44% of the time. My cargo flamechart now looks more like this:

![image](https://user-images.githubusercontent.com/323439/116487539-1d911c80-a888-11eb-88f1-60596767e095.png)

I realize that my workload may be atypical to many others, as it might be quite light. I'm really just doing some matrix and trig operations. But, even with intensive `apply` functions, some performace gains are there to be had for others.

I'm happy to raise a PR and whip it into the kind of shape you'd expect it to be in if you think this is a worthwhile change.

Thanks!

**Comment by stefan-k** [comment]
Thank you for this issue and for looking into it so carefully, I really appreciate it! I have to admit that I haven't been putting as much attention to performance as I should have (it's on my todo list). For some of the areas you pointed out in your analysis I already suspected that they might not be as efficient as they could be (particularly all the code related to `ArgminKV`). I did not expect it to be this severe though! 

I've had a look at your changes and from a first glance I should be able to merge them right away. There are just a few places where I think the style checks in the CI might not pass. Could you do a `rustfmt` run before submitting a PR, please? 

Thanks a lot for the effort! Nice to hear that that someone finds this library useful.

**Comment by sdd** [comment]
Of course! Happy do so.

**Comment by stefan-k** [comment]
Thanks! I published version 0.4.4 with your improvements.

**Comment by sdd** [comment]
Great, appreciate the fast turnaround on this too Stefan. I look forward to helping out where I can again in the future 👍🏼
