### ISSUE TITLE
Bump ndarray version to 0.15

### ISSUE THREAD

**Issue by bytesnake** [argmin-rs/argmin#123]
The `ndarray < 0.15` requirement currently blocks https://github.com/rust-ml/linfa/issues/124. This is currently blocked on https://github.com/rust-ndarray/ndarray-linalg which still has to be published their latest version to `crates.io`

**Comment by stefan-k** [comment]
I typically upgrade to the latest version right away as soon as `ndarray-linalg` supports it. This also indirectly blocks the upgrade of `nalgebra` to 0.27.1 because of `num-complex`.

**Comment by bytesnake** [comment]
good to hear, dependencies are sometimes hard to manage :+1: I primarily opened this issue to pack-ping once it's possible

**Comment by mpizenberg** [comment]
Hi, I'm hitting errors of the kind "trait bound DeserializeOwned is not satisfied ..." when I've upgraded ndarray to 0.15 in my project. I suppose this is because argmin traits are based on 0.14 for now?

**Comment by stefan-k** [comment]
Yes, I'm afraid the error you mentioned is also due to this issue.

**Comment by maoe** [comment]
ndarray-linalg has been updated to [support ndarray-0.15](https://github.com/rust-ndarray/ndarray-linalg/blob/master/CHANGELOG.md#updated-dependencies).

**Comment by stefan-k** [comment]
released version 0.4.6
