### ISSUE TITLE
XorShiftRng has poor statistical quality

### ISSUE THREAD

**Issue by TheIronBorn** [argmin-rs/argmin#138]
`rand_xorshift::XorShiftRng` uses Xorshift128 (also called `xor128`) which is from Marsaglia's original paper. It has significant weaknesses ([[0]](https://doi.org/10.1145%2F1113316.1113319)[[1]](http://pracrand.sourceforge.net/Tests_results.txt)). It was replaced as `rand`'s default noncryptographic PRNG in 2018.

Stochastic optimization requires high quality random numbers and Xorshift128 does not provide that.

argmin could use a sensible default like `rand`'s current `xoshiro256++` or even allow users to select one via traits (I'm willing to write a PR for that).

**Comment by stefan-k** [comment]
I agree that users should be able to select an appropriate algorithm (or provide their own). A trait seems to be a good way to go. I would really appreciate a PR! Let me know if there is anything I can help you with.
