### ISSUE TITLE
ParticleSwarm::new has incorrect parameter documentation

### ISSUE THREAD

**Issue by TheIronBorn** [argmin-rs/argmin#141]
https://github.com/argmin-rs/argmin/blob/1cf4523b9e230dd90ae52618a2ac54bd307da151/src/solver/particleswarm/mod.rs#L46-L51

**Comment by stefan-k** [comment]
Thanks! I will fix this hopefully soon.

**Comment by TheIronBorn** [comment]
I also noticed that Particle Swarm restricts the Hessian type which seems unintended but I don't know.

https://github.com/argmin-rs/argmin/blob/1cf4523b9e230dd90ae52618a2ac54bd307da151/src/solver/particleswarm/mod.rs#L129-L133

**Comment by stefan-k** [comment]
I agree, this seems unnecessary.
