### ISSUE TITLE
Gradient return type problem

### ISSUE THREAD

**Issue by losanc** [argmin-rs/argmin#144]
Hi,

I am a beginner to use this project, I have a rather trivial question, why ` fn gradient(&self, p: &Self::Param) -> Result<Self::Param, Error>` this function returns the type `Param`. 

Although in the Rosenbrock example, `Param` is a vector type, so it doesn't matter. But for example, I have a scenario I know very well how many variables and how many parameters, so I use array instead of vector. For example I I use a one f64 number array `[f64;1]` as parameter, and the function is `x_1+x_2+p[0]`, (this is a stupid function, but only for example), so I know that the gradient should be `[f64;2]`, so, this actually won't work.

**Comment by losanc** [comment]
Hi, 
just want to comment more about this
```rust
struct example{
    x1: f64,
    x2: f64,
}

impl ArgminOp for example{
    /// Type of the parameter vector
    type Param = [f64;1];
    /// Type of the return value computed by the cost function
    type Output = f64;
    /// Type of the Hessian. Can be `()` if not needed.
    type Hessian =();
    /// Type of the Jacobian. Can be `()` if not needed.
    type Jacobian = ();
    /// Floating point precision
    type Float = f64;

    /// Apply the cost function to a parameter `p`
    fn apply(&self, p: &Self::Param) -> Result<Self::Output, Error> {
        Ok(x1+x2 + p[0])
    }

    /// Compute the gradient at parameter `p`.
    fn gradient(&self, p: &Self::Param) -> Result<Self::Param, Error> {
        // it should return [1,1]
        // but type is [f64;1];
    }

    /// Compute the Hessian at parameter `p`.
    fn hessian(&self, p: &Self::Param) -> Result<Self::Hessian, Error> {
// don't need for now
    }
}

```

**Comment by stefan-k** [comment]
Hi,
I'm unsure if I understand your problem correctly. Your function has a single parameter `p[0]` which you optimize over, therefore your gradient should be a single number as well, right? The variables `x1` and `x2` are static numbers which won't change during the optimization, therefore they won't add additional dimensions to the gradient.

**Comment by losanc** [comment]
So, `p` here is actually "independent variable"  of the function, and struct members `x1` and `x2` are parameters of the function?

and I think this should be the correct code, if I want the function f(x1,x2) = x1+x2+1, and gradient to be [1,1], right?

```rust
struct example{
p:f64 // suppose p=1
}

impl ArgminOp for example{
    /// Type of the parameter vector
    type Param = [f64;2];
    /// Type of the return value computed by the cost function
    type Output = f64;
    /// Type of the Hessian. Can be `()` if not needed.
    type Hessian =();
    /// Type of the Jacobian. Can be `()` if not needed.
    type Jacobian = ();
    /// Floating point precision
    type Float = f64;

    /// Apply the cost function to a parameter `p`
    fn apply(&self, x: &Self::Param) -> Result<Self::Output, Error> {
        Ok(x[1]+x[2] + p)
    }

    /// Compute the gradient at parameter `p`.
    fn gradient(&self, x: &Self::Param) -> Result<Self::Param, Error> {
        O([1,1])
    }
}
```

**Comment by stefan-k** [comment]
Yes, this should be more or less correct. (You probably meant `Ok(x[0]+x[1] + p)`.)

However, I'm unsure whether you'll be able to use `[f64; 2]` for your parameters, because so far the required math traits have only been implemented for `Vec` and `ndarray` and `nalgebra` types. If you run into problems (which may depend on the solver you choose) you can either implement those traits for `[f64; 2]` yourself or use a `Vec` instead.

**Comment by losanc** [comment]
Ok, great thanks for your help!  
but to be honest, I think `type Param` is really kind of confusing, intuitively I think changing from `apply(&self, p: &Self::Param)` to `apply(&self, x: &Self::VariableType)` could be easier to understand.

Anyway, thank you again
