### ISSUE TITLE
Simulated Annealing acceptance depends on previous cost, not current

### ISSUE THREAD

**Issue by TheIronBorn** [argmin-rs/argmin#157]
https://github.com/argmin-rs/argmin/blob/6051c4fc3f2b407954f25d3c54fb794fbd5cc619/src/solver/simulatedannealing/mod.rs#L288

There might be some confusion due to the naming of https://github.com/argmin-rs/argmin/blob/6051c4fc3f2b407954f25d3c54fb794fbd5cc619/src/solver/simulatedannealing/mod.rs#L267

**Comment by stefan-k** [comment]
Thanks! You are right, I think `prev_cost` should be used instead of `state.get_prev_cost()` in the comparison. Otherwise comparison would be done against the cost from two iterations before.
