### ISSUE TITLE
Feature Request: BFGS::into_inv_hessian

### ISSUE THREAD

**Issue by millardjn** [argmin-rs/argmin#185]
Hello, I would like to apply the BFGS method to a non convex problem where a greedy approach works well, requiring multiple phases with a gradually increasing dimension. To avoid resetting the learned inv_hessian matrix each time I would like to extract it from the BFGS solver, extend it to the required dimension so as to reuse learnt curvatures and improve performance in the next phase.

A method that returns clone of the inv_hession would also work as the Solver trait already imposes this constraint. If you would like a PR I am happy to tackle this after some feedback on the clone vs de-structure options.

Thanks

**Comment by stefan-k** [comment]
Hi, do I understand correctly that you want to do multiple runs and update the inverse Hessian in between runs? Unfortunately the solver is consumed by the `Executor`, therefore it won't be possible to extract the inverse Hessian after running the optimization. Instead, I would prefer to carry the inverse Hessian from iteration to iteration (just like the Hessian) via an optional field (`inv_hessian` and possibly `prev_inv_hessian`) in the [`IterState`](https://docs.rs/argmin/latest/argmin/core/struct.IterState.html) struct. 

Then one would be able to extract the final Hessian from the `ArgminResult` returned by the `run` method of the `Executor` like this:

```rust
let hessian = result.state().inv_hessian.unwrap();
```
What do you think? Would this help in solving your problem?

**Comment by millardjn** [comment]
Yes multiple runs and increasing the size/dimension of the problem each time, reusing the hessian after padding it out with diagonal ones to the new size. Your solution sounds great, and the right way to do it.

**Comment by stefan-k** [comment]
I just created a PR (#186). Would you mind giving it a try before I merge it? The PR is currently issued against the `main` branch which is quite different to the latest published version (0.5.0). If it makes it easier for you I can also rebase it onto the 0.5.0 version.

**Comment by millardjn** [comment]
Thanks! Those gave me exactly what I needed. I will be implementing the use of it in the next few days.

**Comment by stefan-k** [comment]
I just merged #186. I will backport it and make a new 0.5.1 release (soon). Feel free to reopen this issue if you still happen to have problems.

**Comment by millardjn** [comment]
Hi, just wanted to say thanks again, report a 5-10x speedup, and note that there haven't been any issues under my testing.

**Comment by stefan-k** [comment]
Thanks for the feedback! :)
