### ISSUE TITLE
Can't use TrustRegion with nalgebra types due to Default trait bound

### ISSUE THREAD

**Issue by cfunky** [argmin-rs/argmin#187]
Hello, I'm currently trying to use the `TrustRegion` optimizer with the `Steihaug` subproblem solver and nalgebra's `DVector<f64>` as underlying `ArgminOp::Param` type. Unfortunately, this doesn't seem to be possible, as both the `Solver` impl for `TrustRegion` and the `Steihaug` impl require the `Default` trait to be implemented on the `ArgminOp::Param` type, which is not the case for the dynamically sized nalgebra types. This is very inconvenient. Interestingly, the only place `Default` is actually used is to initialize the `Steihaug` struct which then, as far as I can tell, never uses the initialized default value. A potential fix would be to replace the affected struct fields by `Option<ArgminOp::Param>` and remove the `Default` trait bound. What are your thoughts on this?

**Comment by stefan-k** [comment]
Apologies for the inconvenience and thanks for digging into this. I'm not a huge fan of unwrapping `Option`s but in this case I think it is the only sensible option. I'm always happy to remove unnecessary trait bounds. Would you be willing to provide a PR to fix this? If not I will fix this in the next couple of days.
