### ISSUE TITLE
Loading checkpoints initializes solver

### ISSUE THREAD

**Issue by TheIronBorn** [argmin-rs/argmin#199]
This seems to be unintended and seems to contradict the `Solver::init` documentation:
> This is executed before any iterations are performed. It can be used to perform precomputations

Initialization for many solvers means resetting some values. Particle Swarm Optimization uniformly randomizes the population on initialization

A simple check for `iter == 0` before initializing in `Executor::run` seems a decent fix.

**Comment by stefan-k** [comment]
Great catch, thanks for reporting! I'm currently in the process of refactoring the checkpointing in PR #198 (which has gone a little bit beyond its initial intention). I will include your fix there as well.
