### ISSUE TITLE
Bug in HagerZhangLineSearch

### ISSUE THREAD

**Issue by stefan-k** [argmin-rs/argmin#2]
There seems to be a bug in HagerZhangLineSearch (for instance, running the steepestdescent or nonlinear_cg examples with HagerZhangLineSearch will not converge towards the solution).

**Comment by whereistejas** [comment]
Hi @stefan-k,
I'm interested in this particular issue and would like to help fix it (if it is still relevant). Could you give me some pointers on where to get started? I'm also interested in contributing in general, so please feel to direct to me more urgent or important issues. :)

**Comment by stefan-k** [comment]
Hi @whereistejas ,

thanks for your interest to contribute! It's been a while since I opened this issue, so I can't remember the details anymore. The implementation follows this paper [1]. The code can be found in [2]. I think a good way to move forward is to reproduce the errors by running the [`steepestdescent`](https://github.com/argmin-rs/argmin/blob/master/examples/steepestdescent.rs) and [`nonlinear_cg`](https://github.com/argmin-rs/argmin/blob/master/examples/nonlinear_cg.rs) examples with the `HagerZhangLineSearch`. I suspect a wrong `<`, `>`, `<=` or `>=`. 

While going through the implementation, I noticed a comment that not all stopping criteria are implemented, but I don't think that this is causing the problem. 

If you have any questions feel free to get in touch via the issues or via gitter. I'm happy to help, but I may unfortunately be a bit slow to respond currently!
 
[1] William W. Hager and Hongchao Zhang. "A new conjugate gradient method with guaranteed descent and an efficient line search." SIAM J. Optim. 16(1), 2006, 170-192.
[2] https://github.com/argmin-rs/argmin/blob/master/src/solver/linesearch/hagerzhang.rs

**Comment by whereistejas** [comment]
Hi @stefan-k ,
I compared the output of the two line search methods in [`steepestdescent`](https://github.com/argmin-rs/argmin/blob/master/examples/steepestdescent.rs). 

The output for Hager-Zhang method is: 
```
[
  1.1999999999997424,
  1.2000000000001065
]
```
Where as the output for More-Thuente method is:
```
[
  1.0724442427550391,
  1.151531565672518
]
``` 
So, I'm guessing, this is discrepancy you are talking about?

**Comment by stefan-k** [comment]
Thanks for comparing the code with the paper! I have to admit, I'm a bit lost as to how to proceed. When looking at the [implementation in Julia](https://github.com/JuliaNLSolvers/LineSearches.jl/blob/master/src/hagerzhang.jl) you can see from the comments at the top of the file that the original code (by the author of the paper) "has undergone numerous revisions since publication of the paper". Therefore, this may be a weird edge case which was fixed after publication of the paper (just a guess).
Do you want to have a look at this? It might be pretty tedious to go through the original code and figure out what was changed and what might be going wrong in our implementation. This problem definitely needs fixing, but I can totally understand if you want to tackle a problem which is more interesting and satisfying as your first contribution. If you want to set this issue aside for now and work on something else then I suggest you get in touch in the Gitter channel and we can find something interesting for you.

**Comment by whereistejas** [comment]
Hi @stefan-k,
I'm fine with working on this issue.

On further comparison, I did find some differences:
https://github.com/argmin-rs/argmin/blob/dc2a06ce37f6125515ba296091673356997439e7/src/solver/linesearch/hagerzhang.rs#L327-L338

The if conditions here are different from what is mentioned in the paper:
![double-secant](https://user-images.githubusercontent.com/19555244/104928703-f72a2e00-59c8-11eb-8acf-77febcd808aa.png)

This is my current lead.
