### ISSUE TITLE
Popular solvers missing?

### ISSUE THREAD

**Issue by xemwebe** [argmin-rs/argmin#21]
in search of a solver in rust i stumbled over this very promising library. However, I missed implementations of popular solver I used quite a lot, e.g. Brent's method (for one dimensional  problems) and the methods provided by the ancient minpack package (Levenberg-Marquardt). 

I was wondering what's the reason for that. Is it just a matter of priorities or are the any particular reasons to exclude these algoritms?

**Comment by stefan-k** [comment]
There are no objections against any solver.  This library is in a very early stage and therefore many useful algorithms are still missing. Development has has been a bit slow lately as I've been busy with other responsibilities, but I'm happy to accept pull requests and to provide guidance if you are willing to contribute.

**Comment by xemwebe** [comment]
Okay, I just wanted to make sure it is worth the effort to integrate some of this algorithms into your library.

**Comment by stefan-k** [comment]
Absolutely, all contributions are welcome :)

**Comment by xemwebe** [comment]
I have implemented Brent's method and sent you a pull request. 
However, a few questions remain: I haven't seen any place where I could set the required precision. I would assume that these would be ideally handled by the Executor, automatically stopping the process once the required precision is reached, though this would require some input from the solver. 
Also, Brent's method require to store some state in between iterations, which is now stored in the Brent struct, since IterState does not seem to be appropriate for this purpose.

**Comment by stefan-k** [comment]
Discussion about Brent's method moved to the corresponding PR: #22.

**Comment by stefan-k** [comment]
[Version 0.2.6](https://crates.io/crates/argmin/0.2.6) which includes your implementation of Brent's method was just released.

**Comment by stefan-k** [comment]
Closing this, feel free to reopen if needed.
