### ISSUE TITLE
Option to set append or truncate for ArgminSlogLogger

### ISSUE THREAD

**Issue by TheIronBorn** [argmin-rs/argmin#25]
Current behavior of `ArgminSlogLogger::file` is to truncate the log file on each run.

Sometimes I want to see the logs of a previous run, particularly if using checkpoints,

**Comment by stefan-k** [comment]
Hi,

thanks for your comment! I agree that this should be exposed to the user. I made the [necessary changes to `argmin-core`](https://github.com/argmin-rs/argmin-core/commit/67b7f862f9bce2f01d9b70a58d2c77feeb194c59) and [adapted the docs in `argmin`](https://github.com/argmin-rs/argmin/commit/26ecbf4c42dcce578ee69b46d56757a2c05c1b49). I don't have time to test it thoroughly, therefore I'd appreciate it if you could give me some feedback :)

**Comment by stefan-k** [comment]
Closing this, feel free to reopen if necessary.
