### ISSUE TITLE
docs appear to be outdated

### ISSUE THREAD

**Issue by calbaker** [argmin-rs/argmin#267]
looking at the docs for https://docs.rs/argmin/latest/argmin/solver/neldermead/struct.NelderMead.html#method.with_sd_tolerance, I see: 

> Set sample standard deviation tolerance
>
> Must be non-negative and defaults to EPSILON.
[Example](https://docs.rs/argmin/latest/argmin/solver/neldermead/struct.NelderMead.html#example-1)
```
let nm: NelderMead<Vec<f64>, f64> =
    NelderMead::new(vec_of_parameters).with_sd_tolerance(1e-6)?;
```

but in the source, I see:

```
  /// Set sample standard deviation tolerance
    ///
    /// Must be non-negative and defaults to `EPSILON`.
    ///
    /// # Example
    ///
    /// ```
    /// # use argmin::solver::neldermead::NelderMead;
    /// # use argmin::core::Error;
    /// # fn main() -> Result<(), Error> {
    /// # let vec_of_parameters = vec![vec![1.0], vec![2.0], vec![3.0]];
    /// let nm: NelderMead<Vec<f64>, f64> =
    ///     NelderMead::new(vec_of_parameters).with_sd_tolerance(1e-6)?;
    /// # Ok(())
    /// # }
```

it seems your docs need to be updated to reflect your code or something weird is going on???

**Comment by stefan-k** [comment]
Hi, 
I'm unsure what you mean exactly, as the text seems to be equivalent. Do you mean that the code example is shorter in the documentation compared to the actual docs in the code? This is done deliberately via the `#` in front of the not printed code lines in order to keep the example focused on whats important while making sure that the example still functions as a doctest. 
Or did you mean something else?

**Comment by calbaker** [comment]
Ah, I see that now.  Since this was intentional, I think we can close the issue.  I had an intern who couldn't figure out how to use the solver until I showed him the source code, and we were confused as to why the source has so much more information.  I did not realize that commenting out lines in code examples results in them not appearing in the html docs.   That's  a good trick to have handy.

**Comment by stefan-k** [comment]
For an overview of how to use a solver I suggest having a look at the [corresponding example](https://github.com/argmin-rs/argmin/blob/main/argmin/examples/neldermead.rs) if you haven't seen it already. In the past the docs used to link to the example, but that has unfortunately also caused confusion (#145). 
If you have suggestions on how to improve the documentation I'd be happy to hear them :)

**Comment by calbaker** [comment]
I'll give it some thought.  Documentation has a lot of nuances, and there are often no clear right answers.
