### ISSUE TITLE
Replace `assert!` macros with macros from approx crate

### ISSUE THREAD

**Issue by stefan-k** [argmin-rs/argmin#278]
Currently most assertions in the argmin-math tests use the `assert!` macro, which is somewhat inconvenient for comparing floats. It would be great if those were replaced with the assert macros of the [approx](https://docs.rs/approx/latest/approx/) crate.

Status 

* [x] primitives (#327)
* [x] vec (#327)
* [x] ndarray (#404)
* [x] nalgebra (#404)

**Comment by rpopplewell** [comment]
So for the sake of clarity we're looking for this sort of change for all tests hit by `cargo test -p argmin-math` right?
```                 
// Old
// assert!(((a as $t - res.re) as f64).abs() < std::f64::EPSILON);
// assert!(((-b as $t - res.im) as f64).abs() < std::f64::EPSILON);

// New
assert_relative_eq!(a as f64, res.re as f64, epsilon = std::f64::EPSILON);
assert_relative_eq!(-b as f64, res.im as f64, epsilon = std::f64::EPSILON);
```

**Comment by stefan-k** [comment]
Yes, this is correct! :)
