### ISSUE TITLE
Remove dependency on `failure` and implement custom error types

### ISSUE THREAD

**Issue by stefan-k** [argmin-rs/argmin#31]
It seems as if failure may not be the best choice. Moving to custom error types is however probably quite a big change.

**Comment by rth** [comment]
Not sure if it helps, but https://github.com/dtolnay/anyhow looks to be quite popular for error handling (haven't used it myself).

**Comment by stefan-k** [comment]
@rth Thanks for pointing me to `anyhow`. The move was much less painful than I feared.
