### ISSUE TITLE
Link from the book to argmin-math docs not working

### ISSUE THREAD

**Issue by nluetts** [argmin-rs/argmin#315]
Hi,

I am trying argmin for the first time and have some trouble getting it to run.
While reading through the book, I tried to find out what are the native libraries that need to be installed to work with the combination `argmin-math` and `ndarray`, but I cannot find information on the required libraries (I have cblas, openblas and lapack installed).

Anyhow, I was looking through the documentation and the book and wanted to access the `argmin-math` documentation, but the link in the introduction of the book (https://docs.rs/argmin/latest/argmin-math/) leads to a failed search:

![image](https://user-images.githubusercontent.com/44254521/213111416-fdbeccfa-d7cf-4d76-a2a4-306caff89231.png)

Searching for "argmin-math" does not help:

![image](https://user-images.githubusercontent.com/44254521/213111616-4a779ee9-b422-423b-b940-07f592d4d808.png)

I found the documentation via crates.io on https://docs.rs/argmin-math/latest/argmin_math/

So I guess the link just has to be updated.

**Comment by stefan-k** [comment]
Thanks a lot for this feedback, this is very valuable! I will fix the link probably today.

Regarding the libraries: Typically the `ndarray_*` features of `argmin-math` will pull in `ndarray-linalg`, therefore I suggest having a look at [their github repo](https://github.com/rust-ndarray/ndarray-linalg/tree/ndarray-linalg-v0.14.1) (hopefully this link is correct ;) Note that I deliberately linked an older version, namely the latest one supported by argmin-math. Also note that there is a mistake in the Readme, they mention the wrong version numbers in their Cargo.toml example). They mention which features they offer (and what you need to have installed). Unfortunately this information cannot be found in the [API docs](https://docs.rs/ndarray-linalg/0.14.1/ndarray_linalg/index.html). 

The `ndarray-linalg` feature is only needed for computing the matrix inverse. Therefore, unless you plan to use the (Gauss-)Newton methods, you can instead use one of the `ndarray_*-nolinalg*` features of `argmin-math`, which do not pull in `ndarray-linalg` and you spare yourself the trouble with external libraries. 

I hope this helps, feel free to get in touch if you have any more questions!

**Comment by nluetts** [comment]
Thank you very much for your quick reply!
I tried a bit to get the linking of openblas to work, based on what `ndarray-linalg` provide in their docs/readme, but to no avail.
It looked to me as if I would have needed to make my own `build.rs` file, but Rust is fairly new to me and I didn't want to fight with it.
However, `BrentOpt` did the trick, and it only required implementing the `CostFunction`, so I am happy :-)

**Comment by stefan-k** [comment]
>  I tried a bit to get the linking of openblas to work, based on what `ndarray-linalg` provide in their docs/readme, but to no avail. 

I have had similar experiences with `openblas`, occasionally it works, occasionally it doesn't and I was never able to figure out why. I've had more success with `intel-mkl` and `netlib`. 

> It looked to me as if I would have needed to make my own `build.rs` file, but Rust is fairly new to me and I didn't want to fight with it.

A `build.rs` file shouldn't be necessary.

> However, `BrentOpt` did the trick, and it only required implementing the `CostFunction`, so I am happy :-)

Glad you got it to work! :) I will close this issue, but feel free to reach out if there is anything else I can help you with.
