### ISSUE TITLE
Abort iterations upon a condition on the cost function

### ISSUE THREAD

**Issue by thibc81** [argmin-rs/argmin#318]
Hello

I am trying to figure out the `terminate `function so as to abort the optimization if the cost function returns a certain value.
Is this possible?  I couldn't find an example in the doc or on the git examples folder.

Thanks!

**Comment by stefan-k** [comment]
Are you using one of the available solvers or are you implementing your own? 

The default implementation of `terminate_internal` of the `Solver` trait [automatically checks if a target cost is reached](https://github.com/argmin-rs/argmin/blob/46213202d120db887e22614eef0d1ff30b4cc049/argmin/src/core/solver.rs#L107).

You can set the target cost via the [`target_cost` method](https://docs.rs/argmin/latest/argmin/core/struct.IterState.html#method.target_cost) of `IterState` (or `PopulationState`, depending on which solver you are using), somewhat like this:

```rust
let res = Executor::new(cost, solver)
        .configure(|state| state.param(init_param).max_iters(10).target_cost(0.0))
        .run()?;
```

**Comment by thibc81** [comment]
Thank you for your answer.
I am using PSO, in fact `target_cost ` is effectively what I needed, thanks again.

**Comment by stefan-k** [comment]
I added a little note about `target_cost(...)` [to the example in the book](https://www.argmin-rs.org/book/running_solver.html).
