### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by thibc81** [argmin-rs/argmin#332]
Hi

is there an option to specify a timeout in the Executor to abort the solver after a certain duration?

Thanks!

**Comment by stefan-k** [comment]
Unfortunately no but this would be a great feature! It should be rather easy to add if a bit of "inaccuracy" is acceptable. What I mean by this is that the condition whether the timeout is reached would be checked at the end of each iteration, meaning that in the worst case, it would stop one iteration after the timeout is reached. 
An exact timeout handling would be more difficult to achieve and I don't think it would be worth the additional complexity.
