### ISSUE TITLE
Gauss Newton solver to have option for Gradient and Jacobian

### ISSUE THREAD

**Issue by humphreylee** [argmin-rs/argmin#365]
Appreciate advise on how to handle [Jacobian matrix ](https://en.wikipedia.org/wiki/Jacobian_matrix_and_determinant)that has a single entry; this entry is the derivative of the function f. I tried to use [Gauss Newton](https://docs.rs/argmin/latest/argmin/solver/gaussnewton/struct.GaussNewton.html) solver which requires `Operator` and `Jacobian`. However, `Jacobian` relies on [ArgminInv](https://docs.rs/argmin-math/latest/argmin_math/trait.ArgminInv.html) which has implementation of 2 dims, but not 1 dim.

I tried to use 2 dims (ndarray), and assigned `1` to 2nd array - but is this correct? Is there alternative approach? Thanks.

**Comment by humphreylee** [comment]
Not valid question??

**Comment by humphreylee** [comment]
Perhaps the question is can Gauss Newton solver have option to use (1) Gradient for one variable and (2) Jacobian for mutivariate cost function?

**Comment by humphreylee** [comment]
Or alternatively, implement a 1 dimension for ArgminInv? Does this even make sense?

**Comment by stefan-k** [comment]
Is this maybe related to #345 ?

**Comment by humphreylee** [comment]
Indeed, [#345](https://github.com/argmin-rs/argmin/issues/345) looks very similar to my issue. It was fixed in [346](https://github.com/argmin-rs/argmin/issues/346) in May, 2023, which is after the latest version (0.8.1) which was released in Feb, 2023. Will wait for latest release and test it out. Thanks.

**Comment by stefan-k** [comment]
argmin 0.9.0 should support this.
