### ISSUE TITLE
How to inject custom termination criteria to existing solvers?

### ISSUE THREAD

**Issue by millardjn** [argmin-rs/argmin#370]
Is it possible to terminate one of the crates solvers after evaluating a custom problem specific criteria based on gradient magnitude and cost? I looked at doing it via an observer, but they cannot call terminate_with via a non-mutable borrow.  What is the correct way to do this?

**Comment by stefan-k** [comment]
Unfortunately this currently is not possible, but it is planned (#91). For now, a not so convenient workaround is to write your own Executor (basically copy paste the existing one and add your criteria).

**Comment by millardjn** [comment]
Thanks for the quick reply, and apologies for not seeing that issue, I only searched for "termination" and similar.
