### ISSUE TITLE
Golden section search

### ISSUE THREAD

**Issue by nilgoyette** [argmin-rs/argmin#47]
I coded a [golden section search](https://en.wikipedia.org/wiki/Golden-section_search) in our enterprise project and I wonder if you want it in argmin. It's a simple algorithm with a cost function, nothing complicated.

    fn golden_section_search(
        cost_function: &F,
        min_bound: f32,
        max_bound: f32,
        init_estimate: f32
    ) -> f32 { ... }

I just need to take the time to port it to argmin design and add a test. Are you interested in this contribution?

**Comment by stefan-k** [comment]
Absolutely! Every method is welcome :)

**Comment by nilgoyette** [comment]
There's a part of the code I don't know how to port. There's this condition after the iteration

    if f1 < f2 {
        x1
    } else {
        x2
    }

I'm supposed to run this one time after the stopping condition is met, so after `terminate`. But looking at the `Solver` trait, I see no way of doing that. Did I miss something?

**Comment by stefan-k** [comment]
The current design is indeed a bit inconvenient in that regard. I haven't found a convenient solution to this yet, other than checking for the stopping criteria within the `next_iter` method instead of in `terminate`. This was for instance necessary in [this part of the More Thuente linesearch](https://github.com/argmin-rs/argmin/blob/a72853b7d81ecaffb5a0062705445111d8b9af9f/src/solver/linesearch/morethuente.rs#L330). Essentially you can set the termination reason inside `next_iter` and the executor will stop iterating if it is not `NotTerminated`. This should give you the required freedom.

**Comment by nilgoyette** [comment]
OK, that makes senses. I have another question though. I declared 2 members as

    f1: O::Output,
    f2: O::Output,

I use `ArgminZero` to initialize them and it works.I understand why you use traits for everything (it must work on POD, Vec, ndarray, nalgebra, etc.), but it's tedious when you don't need them. In my case here, the only useful generic would f32/f64, so the user can set the precision.

Anyway, it seems that I can't compare them

    if self.f2 < self.f1 {

    binary operation `<` cannot be applied to type `<O as core::ArgminOp>::Output`
    note: an implementation of `std::cmp::PartialOrd` might be missing for `<O as core::ArgminOp>::Output`

Did you write a trait for that? I can't find it.

**Comment by stefan-k** [comment]
So far I have solved this by assuming that `O::Output` will be `f64`, as shown [in this line of code](https://github.com/argmin-rs/argmin/blob/a72853b7d81ecaffb5a0062705445111d8b9af9f/src/solver/linesearch/morethuente.rs#L202). This isn't ideal, but for now I hoped this would be acceptable. A comparison trait would probably be more useful.

> I understand why you use traits for everything (it must work on POD, Vec, ndarray, nalgebra, etc.), but it's tedious when you don't need them.

I agree! It was also tedious to implement ;)

**Comment by stefan-k** [comment]
Closing because #49 was merged.
