### ISSUE TITLE
Make errors public

### ISSUE THREAD

**Issue by rasa200** [argmin-rs/argmin#52]
# Background
Hi there!! Thank you for the great work!! 

I am starting to use the crate and run into the following problem:
Implementing `ArgminOp`, the method `apply`, I would like to correctly handle errors. Then, I need to return an `argmin::core::Error`, but it is private. I even tried with the suitable variant of `argmin::core::ArgminError`, but it is also private. 

# Request
Make errors public and easy to construct. And add the corresponding indications in the documentation when implementing the `ArgminOp` trait.

# Example
I would like for something like this to work.
```
use argmin::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Serialize, Deserialize)]
pub struct MyProblem; 

impl ArgminOp for MyProblem {
    type Param = ();
    type Output = ();
    type Hessian = ();
    type Jacobian = ();
    type Float = ();

    /// Apply the cost function to a parameter `p`
    fn apply(&self, _p: &Self::Param) -> Result<Self::Output, Error> {
        argmin::core::ArgminError::InvalidParameter{text: String::from("MyProblem does not take this parameters")}
        // or better
        //  argmin::error::ArgminError::InvalidParameter::new("Error message")
    }
}
```

**Comment by stefan-k** [comment]
Hi! 

`Error` and `ArgminError` should be public. I just tried the following, which works for me:

```rust
use argmin::prelude::*;

impl ArgminOp for MyProblem {
    type Param = f64;
    type Output = f64;
    type Hessian = ();
    type Jacobian = ();
    type Float = f64;

    fn apply(&self, p: &Self::Param) -> Result<Self::Output, Error> {
        Err(ArgminError::InvalidParameter {
            text: String::from("bla"),
        }
        .into())
    }
}
```

However, the ergonomics are far from ideal, I agree. I will think about this. 
Alternatively, you should be able to implement your own errors if you want to. 

Could you show me the compile error, please?

**Comment by stefan-k** [comment]
Which version are you using? The current master branch or 0.2.6? Your snippet suggests the master branch, but your problem suggests 0.2.6 ;) 

I would suggest to use the current master branch, as the current release is quite old and outdated. I'm planning to publish a new release soon.

**Comment by rasa200** [comment]
Perfect!! 
I am so sorry, I got mixed the two versions (working on 0.2.6). Working on the master branch works as you say :) 

So, case solved.
Happy to hear about the new release! :D 

By the way, did you notice that the documentation is "broken"? I mean, from [crates.io](https://crates.io/crates/argmin), the documentation link is broken. Is it a problem with docs.rs?

(I can open other issue for this if you want)

**Comment by stefan-k** [comment]
Glad I could help! I'm very sorry about the confusion!

Thanks for informing me about the broken documentation, I will investigate it ;)

**Comment by rasa200** [comment]
Thanks to you!!
