### ISSUE TITLE
ParticleSwarm usage

### ISSUE THREAD

**Issue by ethanhs** [argmin-rs/argmin#63]
Hi! I am very excited to try out the ParticleSwarm optimizer. It seems however that it only provides 2 values to the objective function (presumably x/y coordinates). Would it be possible to use it for higher dimensional optimization?

**Comment by stefan-k** [comment]
@jjbayer are you able to help with this? Thanks!

**Comment by stefan-k** [comment]
I've had a quick look and I can't see anything which should limit you in the number of parameters. The only thing I can think of being a problem is the `visualizer` feature, which is limited to 2D problems. Are you by any chance using this feature?

**Comment by MattBurn** [comment]
Hi, I have used the particle swarm optimiser with n features in the past here is an example of my use of the optimiser:
```rust
let solver = ParticleSwarm::new(
    (vec![param_min; self.n_feat], vec![param_max; self.n_feat]),
    swarm_size,
    c1,
    c2,
    inertia,
)?;
let cost = self.clone();

let executor = Executor::new(cost, solver, self.get_params()).max_iters(1000);
executor.run()?
```
As @stefan-k said, I the example in [examples/particleswarm.rs](https://github.com/argmin-rs/argmin/blob/master/examples/particleswarm.rs) is only limited to 2D for the visualiser.

Hope this helps.

**Comment by ethanhs** [comment]
Hey @MattBurn thanks! I totally misunderstood the parameters to the new function, so I seem to have limited it myself. Thanks for the example, that solves my problem!
