### ISSUE TITLE
NelderMead requires Default but doesn't need it

### ISSUE THREAD

**Issue by vadixidav** [argmin-rs/argmin#72]
I want to use the nalgebra support for `argmin` in master, but I am having some difficulties. Specifically, I want to use [`NelderMead` optimization](https://docs.rs/argmin/0.3.1/argmin/solver/neldermead/struct.NelderMead.html), but I have found that it requires the param to be Default. I am using [`nalgebra::DMatrix`](https://docs.rs/nalgebra/0.22.0/nalgebra/base/type.DMatrix.html). `DMatrix` does not implement `Default`. I looked at the implementation of `NelderMead`, and it seems that it does not utilize the `Default` bound at all. Is it possible to remove this bound so that I can use `DMatrix` with it. Thank you!

**Comment by vadixidav** [comment]
If this is okay, I can just submit a PR that removes this trait bound.

**Comment by vadixidav** [comment]
I went ahead and just made the PR since its a 2 line change and takes basically no time. Feel free to accept or reject.

**Comment by stefan-k** [comment]
Looks good to me, thanks!
